name: Analyze main branch with SonarQube

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Analyze code with SonarQube
        uses: sonarsource/sonarqube-scanner-github-action@master
        with:
          sonar.host.url: ${{ secrets.SONAR_URL }}
          sonar.login: ${{ secrets.SONAR_TOKEN }}
          sonar.projectKey: opensource-test-pr
          sonar.projectName: opensource-test-pr
          sonar.branch.name: main
          sonar.sources: src/main
          sonar.issuesReport.console.enable: true
          sonar.tests: src/test
          sonar.language: java
          sonar.java.binaries: build/libs
          sonar.sourceEncoding: UTF-8
          sonar.scm.provider: git
